ci(linux): skip some flaky `git svn` tests
t9128.3 seems to fail frequently with

	Copying file:///git/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/trunk at r2 to file:///git/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/branches/a...
	Found possible branch point: file:///git/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/trunk => file:///git/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/branches/a, 2
	Found branch parent: (refs/remotes/origin/a) f0b328ca160440be8ec89839bc42e64415c982d0
	Following parent with do_switch
	Successfully followed parent
	r3 = a90f0519be391f542c14be690e27185cd55c3017 (refs/remotes/origin/a)
	error: git-svn died of signal 11
	not ok 3 - git svn branch tests

and t9167.3 seems to fail in a similar manner.

Since we don't care about `git svn` in MinGit, let's just ignore this
problem.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>